- id: redeploy
  execute-command: /config/scripts/redeploy.sh
  command-working-directory: '{{getenv "WEBHOOK_WORKDIR" | js}}'
  pass-arguments-to-command:
    - source: payload
      name: head_commit.id
    - source: payload
      name: pusher.name
    - source: payload
      name: pusher.email
    - source: payload
      name: repository.name
  response-message: Deploying...
  trigger-rule:
    and:
      - match:
          type: value
          value: refs/heads/main
          parameter:
            source: payload
            name: ref
      - match:
          type: payload-hmac-sha256
          secret: '{{getenv "REDEPLOY_HMAC" | js}}'
          parameter:
            source: header
            name: X-Hub-Signature-256
